name = Base
description = A simple base 3 column layout demonstrating mobile first and Susy.
preview = preview.png
template = base-layout

; ========================================
; Stylesheets
; ========================================
stylesheets[all][] = css/apex.normalize.css
stylesheets[all][] = css/apex.hacks.css
stylesheets[all][] = css/layouts/base/base.layout.css
stylesheets[all][] = css/apex.styles.css
stylesheets[all][] = css/apex.no-query.css

; ========================================
; Scripts
; ========================================
scripts[] = js/apex.behaviors.js

; ========================================
; Regions
; ========================================
regions[branding]         = Branding
regions[header_top_left]  = Header Top Left
regions[header_top_right] = Header Top Right
regions[search]           = Search
regions[header]           = Header
regions[cart]             = Cart
regions[navigation]       = Navigation bar
regions[banner]           = Banner
regions[highlighted]      = Highlighted
regions[help]             = Help
regions[content_top]      = Content Top
regions[content]          = Content
regions[content_bottom]   = Content Botoom
regions[sidebar_first]    = First Sidebar
regions[sidebar_second]   = Second Sidebar
regions[footer_first]     = Footer first
regions[footer_second]    = Footer second
regions[footer_third]     = Footer third
regions[footer_fourth]    = Footer fourth
regions[footer]           = Footer
