<?php

/**
 * Author: Romualdo Dasig <dasig.rg@a5project.com>
 */

/**
 * Implements hook_preprocess_views_view().
 */
function tlustycrm_preprocess_views_view(&$vars) {
  $view = $vars['view'];
  
  if ($view->name == 'request') {
    drupal_add_css(drupal_get_path('module', 'tlustycrm') . '/css/tlustycrm.css');
  }
}

/**
 * Get cycle time of a Request.
 * 
 * @param $from
 * @param $to
 */
function tlustycrm_get_cycle_time($from, $to) {
  $dtF = new \DateTime("@$from");
  $dtT = new \DateTime("@$to");
  return $dtF->diff($dtT)->format('%ad %hh %im');
}

/**
 * Implements hook_rules_action_info().
 */
function tlustycrm_rules_action_info() {
  return array(
    'tlustycrm_log_request' => array(
      'label' => t("Log changes to request's state."),
      'arguments' => array(
        'unchanged_node' => array('type' => 'node', 'label' => t('Unchanged content')),
        'node' => array('type' => 'node', 'label' => t('Content')),
        'user' => array('type' => 'user', 'label' => t('User')),
      ),
      'group' => t('Custom'),
    ),
  );
}

/**
 * Log change on request's state.
 * 
 * @param string $user
 */
function tlustycrm_log_request($unchanged_node, $node, $user) {
  watchdog('request', $user->name . ' changed the state of Request: ' . $node->title . ' from ' . $unchanged_node->field_state[LANGUAGE_NONE][0]['value'] . ' to ' . $node->field_state[LANGUAGE_NONE][0]['value'] . '.');
}